exp_dir: '' # gets set in the trainer

# seed - set to -1 to choose random seed
seed: 521

# wandb configurations
use_wandb: False
wandb_group: ''
wandb_name: ${hp_name}
wandb_entity: 'gaze-rl'
wandb_project: 'gaze_rl'
wandb_notes: ''
wandb_tags: 
  - 'gaze_rl'
group_name: ''

# evaluation
eval_every: -1 

# number of update steps between logging to terminal
log_terminal_every: 50_000
save_every: 50_000

# number of total evaluation steps to run
num_evals: 30
disable_tqdm: False 
run_eval_rollouts: False
skip_first_eval: False 

# rollouts
num_eval_rollouts: 20
num_eval_rollouts_render: 2 
log_rollout_videos: False
video_fps: 20  

# total number of gradient updates
num_updates: 400_000
num_eval_steps: 500

# resume training
load_from_ckpt: False 
ckpt_step: -1
mode: 'train'
log_level: 'info'
enable_jit: True
save_key: null
best_metric: 'max'

clip_grad_norm: 5.0  

# optimizer and scheduling
optimizer:
  name: 'AdamW'
  params:
    lr: 3e-4
    eps: 1e-5
    weight_decay: 0.0
    betas: [0.9, 0.999]
  num_warmup_steps: 25_000

# lr scheduling
lr_scheduler:
  name: 'CosineAnnealingLR'
  params:
    T_max: ${num_updates}
    eta_min: 1e-5

debug: False
name: null 
hp_name: null

# set the directory where the output files get saved
hydra:
  job:
    name: ${hp_name}

  output_subdir: null
  run:
    dir: results/${name}/${hp_name}/${now:%Y-%m-%d}-${now:%H-%M-%S}
  
  sweep:
    dir: results/${name}/${now:%Y-%m-%d}-${now:%H-%M-%S}
    subdir: ${hp_name}

defaults:
  - env: mujoco
  - data: base
  - custom
  - override hydra/job_logging: disabled
  - override hydra/launcher: local
  - _self_