num_updates: 400_000
log_terminal_every: 20_000 
run_eval_rollouts: True
log_rollout_videos: True

name: bc 
hp_name: ${name}_nt-${data.num_trajs}_gp-${model.gaussian_policy}

data:
  data_type: transitions

defaults: 
  - base
  - model: bc
  - _self_